config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'landing', to: 'pages#landing'
  get 'no_clan', to: 'pages#no_clan'
  resources :challenges, only: [ :show ]
  resources :users, only: [ :show ]
  resources :clans, only: [ :show ] do
    post :add_user, on: :member
    resources :activities, only: [ :index ]
  end
  resources :user_challenges, only: [ :index, :create, :show] do
    member { patch :accept, :decline, :validate, :drop }
  end
  resources :invitations, only: [:create, :update]
  resources :activities do
    post :read, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_challenge.rb
class UserChallenge < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
  scope :get_user_challenges, -> (user, status) {where(user: user, status: status)}
  has_many :activities, dependent: :destroy
  after_update :update_score_user

  DIFFICULTY_SCORES = [50, 100, 150]

  def update_score_user
    return unless status == "validated"

    score_user = user.score
    user.update(score: score_user + DIFFICULTY_SCORES[challenge.difficulty - 1])
    return unless user.clan

    score_clan = user.clan.score
    user.clan.update(score: score_clan + DIFFICULTY_SCORES[challenge.difficulty - 1])
  end
end

app/controllers/user_challenges_controller.rb
class UserChallengesController < ApplicationController
  before_action :set_user_challenge, only: [:show, :accept, :decline, :drop, :validate]

  def index
    @user_challenges = UserChallenge.get_user_challenges(current_user, 'accepted')
  end

  def create
    @user_challenges_ongoing = UserChallenge.get_user_challenges(current_user, 'accepted').count
    @undone_challenges = (Challenge.all - current_user.challenges).first(7 - @user_challenges_ongoing)
    if @undone_challenges.empty?
      flash[:alert] = "Tu as réalisé tous les challenges de Seed of Change, félications !"
      redirect_to user_challenges_path
    else
      @user_challenges = @undone_challenges.map { |challenge| UserChallenge.create(challenge: challenge, user: current_user, status: 'pending')}
      redirect_to user_challenge_path(@user_challenges.first)
    end
  end

  def show
    @disable_bell = true
    @user_challenges_ongoing = UserChallenge.get_user_challenges(current_user, 'accepted').count
    @current_week = Date.today.strftime('%d %b %Y')
    @already_users = User.includes(:user_challenges).where(clan: current_user.clan, user_challenges: { status: 'validated', challenge: @user_challenge.challenge })
  end

  def accept
    @user_challenge.update(status: "accepted")
    action_after_update
  end

  def decline
    @user_challenge.update(status: "declined")
    action_after_update
  end

  def drop
    @user_challenge.update(status: "dropped")
    redirect_to user_challenges_path
  end

  def validate
    @user_challenge.update(status: "validated")
    clan_notification if current_user.clan
    @validated_challenges = Challenge.includes(user_challenges: :user).where(category: @user_challenge.challenge.category, user_challenges: { user: current_user, status: "validated" })
    @category_count = @validated_challenges.count
    if @category_count == 6 || @category_count == 11 || @category_count == 16
      redirect_to user_challenges_path, notice: "Bravo, tu as gagné #{@user_challenge.challenge.difficulty * 50} points 🥳 et un badge #{@user_challenge.challenge.category} 🏆 !"
    else
      redirect_to user_challenges_path, notice: "Bravo, tu as gagné #{@user_challenge.challenge.difficulty * 50} points ! 🥳🥳🥳 "
    end
  end

  private

  def clan_notification
    other_users = current_user.clan.users.excluding(current_user)
    broadcast_notification
    other_users.each { |user| Activity.create(user: user, user_challenge: @user_challenge) }
    return unless check_position_change == true

    Activity.create(user: @higher_user, user_challenge: @user_challenge, username: current_user.username)
  end

  def broadcast_notification
    NotificationChannel.broadcast_to(
      current_user.clan,
      render_to_string(partial: "shared/notifications", locals: { status: true, user: @user_challenge.user })
    )
  end

  def check_position_change
    users = current_user.clan.users.order(score: :desc)
    user_position = users.index(current_user)
    return if user_position.zero?

    @higher_user = users[user_position - 1]
    higher_score = @higher_user.score
    updated_score = (@user_challenge.challenge.difficulty * 50) + current_user.score
    updated_score > higher_score
  end

  def set_user_challenge
    @user_challenge = UserChallenge.find(params[:id])
  end

  def action_after_update
    @user_challenges_ongoing = UserChallenge.get_user_challenges(current_user, 'accepted').count
    @user_challenges_pending = UserChallenge.get_user_challenges(current_user, 'pending')
    if @user_challenges_ongoing >= 5
      @user_challenges_pending.destroy_all
      render "user_challenges/end"
    elsif @user_challenges_pending.empty?
      render "user_challenges/end"
    else
      redirect_to user_challenge_path(@user_challenges_pending.first)
    end
  end
end

app/views/user_challenges/end.html.erb
<div class="end-container">
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    <h1 class="text-center golden-title"> La sélection est terminée </h1>
    <div class="display-1 text-center mt-3">
      <span class="iconify seed " data-icon="tabler:seeding" data-inline="false"></span>
    </div>

    <%= link_to "Retour", user_challenges_url(@user_challenges), class: "button-gold mt-5" %>
</div>

app/views/user_challenges/index.html.erb
  <h1 class="page-title">Défis en cours</h1>

  <% if @user_challenges.empty? %>
    <div class="d-flex flex-column justify-content-center no-challenge">
      <p>Tu n'as pas de défi <br> en cours.</br> Ajoutes-en !</p>
      <%= link_to user_challenges_path, class: "button button-add mx-auto mt-5", :method => :post do %>
        <i class="fas fa-plus"></i>
      <% end %>
     </div>
  <% else %>
    <div class="challenges-cards">
      <% @user_challenges.each do |user_challenge| %>
        <%= link_to challenge_path(user_challenge.challenge) do %>
          <div class="card-challenge">
            <div class="d-flex justify-content-between">
              <h1><%= user_challenge.challenge.name %>  </h1>
              <%= link_to drop_user_challenge_path(user_challenge), method: :patch, data: {:confirm => "C'était pourtant un super challenge...",  title: 'Tu es sûr de toi ?'}  do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
            <div class="card-info">
              <h2 class="<%= label_category(user_challenge.challenge.category) %>"><%= user_challenge.challenge.category %></h2>
              <%= render 'shared/difficulty', level: user_challenge.challenge.difficulty %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="btn-add-bar">
      <% unless @user_challenges.count == 5  %>
        <%= link_to user_challenges_path, class: "button button-add", :method => :post do %>
          <i class="fas fa-plus"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>

app/views/user_challenges/show.html.erb
<div class="current-week">
  <h2> semaine du <%= @current_week %></h2>
</div>

<div class="user-challenge-count">
  <subtitle> <%= @user_challenges_ongoing %>/5</subtitle>
</div>

<div class="card-show">

  <h1><%= @user_challenge.challenge.name %></h1>
  <br>
  <div class="d-flex justify-content-between align-items-center first-info">
    <h2 class="<%= label_category(@user_challenge.challenge.category) %>"><%= @user_challenge.challenge.category %></h2>
    <div class="avatars">
      <% @already_users.first(2).each do |user| %>
        <%= image_tag "https://res.cloudinary.com/dwbej2js2/image/upload/v1613148306/SeedOfChange%20-%20Avatar/#{user.first_name}.png", class: "avatar avatar-challenge", alt: "avatar" %>
      <% end %>
      <% if @already_users.count > 2 %>
        <p class="avatar">+<%= @already_users.count - 2 %></p>
      <% end %>
    </div>
  </div>

  <div class="compulsory-info">
    <div class="d-flex justify-content-between">
      <div class="price-duration">
        <p><i class="fas fa-shopping-cart"></i>    <%= @user_challenge.challenge.price %> €</p>
        <p><i class="fas fa-hourglass-start"></i>    <%= pluralize(@user_challenge.challenge.duration, 'minute') %></p>
      </div>
        <div class="difficulty">
          <%= render 'shared/difficulty', level: @user_challenge.challenge.difficulty %>
        </div>
    </div>
    <p><%= @user_challenge.challenge.description %></p>
  </div>

  <% if @user_challenge.challenge.necessary_items.present? || @user_challenge.challenge.how_to.present? ||
    @user_challenge.challenge.tips.present? || @user_challenge.challenge.where_to.present? %>
    <a class="know-more collapsed" data-toggle="collapse" href="#textCollaspe" role="button" aria-expanded="false" aria-controls="textCollaspe"><strong>En savoir plus</strong></a>

    <div class="collapse" id="textCollaspe">

      <div class="other-info">

        <% if @user_challenge.challenge.necessary_items.present? %>
          <div class="necessary-items">
            <h2>Liste de course</h2>
            <% @user_challenge.challenge.necessary_items.each do |item| %>
            <ul>
              <li>
                <%= item %>
              </li>
            </ul>
            <% end %>
          </div>
        <% end %>

        <% if @user_challenge.challenge.how_to.present? %>
          <div class="how-to">
            <h2>Comment faire ?</h2>
            <% @user_challenge.challenge.how_to.each do |step| %>
            <ul>
              <li>
                <%= step %>
              </li>
            </ul>
            <% end %>
          </div>
        <% end %>

        <% if @user_challenge.challenge.tips.present? %>
          <div class= "tips">
            <h2>Petite astuce</h2>
            <%= @user_challenge.challenge.tips %>
          </div>
        <% end %>

        <% if @user_challenge.challenge.where_to.present? %>
          <div class= "useful-links">
            <h2>Liens utiles</h2>
            <ul>
              <% @user_challenge.challenge.where_to.each do |link|%>
                <li>
                  <a href="<%= link %>"><%= link %></a>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>

      </div>

    </div>

  <% end %>

</div>


<div class="buttons">
  <%= link_to decline_user_challenge_path(@user_challenge), class: "button-decline", method: :patch do %>
    <i class="fas fa-times-circle"></i>
  <% end %>
  <%= link_to accept_user_challenge_path(@user_challenge), class: "button-accept", method: :patch do %>
    <i class="fas fa-check "></i>
  <% end %>
</div>