config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'landing', to: 'pages#landing'
  get 'no_clan', to: 'pages#no_clan'
  resources :challenges, only: [ :show ]
  resources :users, only: [ :show ]
  resources :clans, only: [ :show ] do
    post :add_user, on: :member
    resources :activities, only: [ :index ]
  end
  resources :user_challenges, only: [ :index, :create, :show] do
    member { patch :accept, :decline, :validate, :drop }
  end
  resources :invitations, only: [:create, :update]
  resources :activities do
    post :read, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_card_clan.html.erb
<div class="row align-items-center">
  <div class="card-clan row <%= 'current-user' if local_assigns[:current_user_style] %>">

    <div class= "col-2">
      <%= cl_image_tag member.avatar.key, class: "avatar", alt: "avatar" %>
    </div>

    <div class="info-member col-8">
      <% if index == 0 %>
        <h2><%= member.username %> <i class="fas fa-crown crown gold"></i></h2>
      <% elsif index == 1 %>
        <h2><%= member.username %> <i class="fas fa-crown crown silver"></i></h2>
      <% elsif index == 2 %>
        <h2><%= member.username %> <i class="fas fa-crown crown bronze"></i></h2>
      <% else %>
        <h2><%= member.username %></h2>
      <% end %>
      <subtitle><strong><%= member.score %></strong> points</subtitle>
    </div>

    <div class="col-2">
      <p><%= index + 1 %> </p>
    </div>

  </div>
</div>

app/views/shared/_difficulty.html.erb
<% leaves = Array.new(3) { render 'shared/empty_leaf' } %>
<% level.times do |n| %>
  <% leaves[n] = '<i class="fas fa-leaf"></i>' %>
<% end %>
<div class="difficulty">
  <%= leaves.join.html_safe %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_invitation.html.erb
<div class="card-invitation">
    <p>Tu as reçu une invitation pour être membre du clan : <strong><%= @invitation.clan.name %></strong></p>
  <div class="d-flex justify-content-center">
    <%= link_to invitation_path(@invitation, status: "declined"), class: "button-decline", method: :patch do %>
      <i class="fas fa-times-circle"></i>
    <% end %>
    <%= link_to invitation_path(@invitation, status: "accepted"), class: "button-accept", method: :patch do %>
      <i class="fas fa-check"></i>
    <% end %>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">
<%= favicon_link_tag 'icons/favicon-32x32.png' %>

app/views/shared/_meta_tags.html.erb
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:image:src" content="<%= meta_image %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-seed">

  <div class="<%= 'active' if controller.controller_name == 'pages' && controller.action_name == 'home' %> navbar-element">
    <% if current_page?(root_path) %>
      <%= link_to_unless_current '<i class="fa fa-home"></i><subtitle> Accueil </subtitle>'.html_safe, (landing_path), class: "navbar-element" %>
    <% else %>
      <%= link_to_unless_current '<i class="fa fa-home"></i><subtitle> Accueil </subtitle>'.html_safe, (root_path), class: "navbar-element" %>
    <% end %>
  </div>

  <div class="<%= 'active' if controller.controller_name == 'user_challenges' || controller.controller_name == 'challenges' %> navbar-element">
    <%= link_to_unless_current '<i class="fas fa-seedling"></i> <subtitle>Défis</subtitle>'.html_safe, user_challenges_path, class: "navbar-element" %>
  </div>

  <% if current_user %>

    <% if current_user&.clan %>

      <div id="navbar-clan" class="<%= 'active' if controller.controller_name == 'clans' || controller.controller_name == 'activities' %> navbar-element">
        <%= link_to_unless_current '<i class="fas fa-heart"></i> <subtitle>Clan</subtitle>'.html_safe, clan_activities_path(current_user.clan), class: "navbar-element", 'data-turbolinks': false %>
        <div id="notif" data-clan-id="<%= current_user.clan.id %>" data-current-user="<%= current_user.id %>" data-file='<%= audio_url('hirondelle.wav') %>' >
          <% if current_user.activities.where(read: false).empty? %>
            <%= render 'shared/notifications', status: false, user: nil %>
          <% else %>
            <i class="fa-circle fas"></i>
          <% end %>
        </div>
      </div>

    <% else %>
      <div class="<%= 'active' if controller.controller_name == 'pages' && controller.action_name == 'no_clan' %> navbar-element">
        <%= link_to_unless_current '<i class="fas fa-heart"></i> <subtitle>Clan</subtitle>'.html_safe, (no_clan_path), class: "navbar-element", 'data-turbolinks': false %>
      </div>
    <% end %>


    <div class="<%= 'active' if controller.controller_name == 'users' && controller.action_name == 'show' %> navbar-element">
      <%= link_to_unless_current '<i class="fas fa-user"></i> <subtitle>Profil</subtitle>'.html_safe, user_path(current_user), class: "navbar-element" %>
    </div>

  <% end %>

</div>

app/views/shared/_navbarsecondaryclan.html.erb
<%
  ranking = params[:tab] == "ranking"
%>

<div class="switch-button" <%= "data-turbolinks-permanent" if keep_navbar? %>  id="switch-button">
  <span class="active" style="left: <%= ranking ? 50 : 0  %>%;"></span>
  <%= link_to "Activités", clan_activities_path(current_user.clan), class: "switch-button-case left" %>
  <%= link_to "Classement", clan_path(current_user.clan), class: "switch-button-case right" %>
</div>

app/views/shared/_notifications.html.erb
<div class="d-none" data-user="<%= user&.id %>">
</div>
<i class="<%= status ? 'fa-circle fas' : '' %>"></i>

app/views/shared/_progression_bar.html.erb
<p class="progression-bar-level-first"> l </p>
<p class="progression-bar-level-second"> l </p>
<p class="progression-bar-level-third"> l </p>
<p class="progression-bar-level-fourth"> l </p>