config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'landing', to: 'pages#landing'
  get 'no_clan', to: 'pages#no_clan'
  resources :challenges, only: [ :show ]
  resources :users, only: [ :show ]
  resources :clans, only: [ :show ] do
    post :add_user, on: :member
    resources :activities, only: [ :index ]
  end
  resources :user_challenges, only: [ :index, :create, :show] do
    member { patch :accept, :decline, :validate, :drop }
  end
  resources :invitations, only: [:create, :update]
  resources :activities do
    post :read, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/clan.rb
class Clan < ApplicationRecord
  validates_presence_of :name
  has_many :users, dependent: :nullify
  has_many :user_challenges, through: :users
  has_many :invitations, dependent: :destroy
end

app/controllers/clans_controller.rb
class ClansController < ApplicationController
  def show
    @clan = current_user.clan
    @members_by_position = @clan.users.order(score: :desc)
    @invitation = current_user.invitations.where(status: "pending").last
  end
  # def add_user
  #   user = User.find_by(username: params[:username])
  #   @clan = Clan.find(params[:id])
  #   if user && user.clan.nil?
  #     user.clan = @clan
  #     user.save
  #     flash[:alert] = "Nous avons bien ajouté #{user} au clan #{@clan}"
  #   elsif user
  #     flash[:alert] = "#{user.capitalize} fait déjà partie d'un clan"
  #   else
  #     flash[:alert] = "Nous n'avons pas trouvé #{user}. "
  #   end
  #   redirect_to clan_path @clan
  # end
end

app/views/clans/show.html.erb
<!-- Navbar secondaire -->
<div class="user-container mt-5 text-center p-3">
  <%= render "shared/navbarsecondaryclan" %>
  <br>
  <%= render 'shared/invitation' if @invitation %>
  <h1><%= @clan.name %></h1>
</div>

<!-- Image représentative du niveau du clan -->
<div class="clan-level mb-2 position-relative">
  <% if @clan.score < 6800 %>
    <%= image_tag "pollue.png", width: 200 %>
  <% else %>
      <%= image_tag "moins pollue.png", width: 200 %>
  <% end %>
 </div>

<!-- Nombre de members et total points -->
<div class="d-flex justify-content-around pb-2">
  <div class="clan-points pb-0 mb-0">
    <%= @members_by_position.count %> / 25
    <p class="white">membres</p>
  </div>
  <div class="clan-points pb-0 mb-0">
    <%= @clan.score %>
    <p class="white">points</p>
  </div>
</div>

<!--  Classement des membres -->
<div class="members-list">
  <ul>
    <% @members_by_position.each_with_index do |member, index| %>
      <li>
        <% if member.username == current_user.username %>
          <%= link_to user_path(current_user) do  %>
            <%= render 'shared/card_clan', member: member, index: index, current_user_style: true %>
          <% end %>
        <% else %>
          <%= render 'shared/card_clan', member: member, index: index %>
        <% end %>
      </li>
    <% end %>
  </ul>

<!-- Bouton trigger modal pour invitation -->
  <div class="text-center">
    <button type="button" class="button-clan text-center text-white" data-toggle="modal" data-target="#exampleModalCenter">
      J'agrandis mon clan !
    </button>
  </div>

<!-- Modal d'invitation -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Quelle formidable personne souhaites-tu ajouter à ton clan ?</p>
          <br>
          <%= form_tag  invitations_path, method: :post do %>
            <%= text_field_tag :username,
              params[:username],
              class: "form-control",
              placeholder: "CocoDu77"
            %>
            <br> <br>
            <%= submit_tag "Je l'ajoute !", class: "button-modal-clan text-center text-white" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>